plugins {
	id 'net.neoforged.moddev' version '2.0.147'
}

version = project.version
group = project.group

base {
	archivesName = project.archives_base_name
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
	withSourcesJar()
}

repositories {
	mavenCentral()
	maven {
		name = 'NeoForged'
		url = 'https://maven.neoforged.net/releases'
	}
}

neoForge {
	version = project.neoforge_version

	runs {
		client {
			client()
		}
	}
}

dependencies {
	implementation "net.neoforged:neoforge:${project.neoforge_version}"
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	it.options.encoding = 'UTF-8'
}

processResources {
	def version = project.version
	inputs.property "version", version
	inputs.property "mc_version", project.minecraft_version
	inputs.property "neoforge_version", project.neoforge_version

	filesMatching("META-INF/neoforge.mods.toml") {
		expand "version": version,
				"mc_version": project.minecraft_version,
				"neoforge_version": project.neoforge_version
	}
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archives_base_name}" }
	}
}
