modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "argon"
version = "${version}"
displayName = "Argon"
authors = "HasaanAmerRavid"
description = '''
Lite jigsaw layout optimizer and frame cadence for Minecraft 26.3. Does not change vanilla structure size or seeds.
'''
logoFile = "assets/argon/icon.png"

[[mixins]]
config = "argon.mixins.json"

[[dependencies.argon]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.argon]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version},)"
ordering = "NONE"
side = "BOTH"
